### ISSUE TITLE
WP CLI w/ Memcache throws an error

### ISSUE THREAD

**Issue by jtsternberg** [SyntaxC4-MSFT/WPCLIExtension#1]
[Screenshot](http://b.ustin.co/Z6KI) (screenshot fixed)

**Comment by SyntaxC4** [comment]
When extensions are loaded using `PHP_EXTENSIONS` App Setting these extensions are only reflected in the FastCGI Process and would not be loaded as part of the CLI.

I have updated the extension to enable the use of a `PHP_INI_SCAN_DIR` which will allow extensions to be loaded at the System level (as they were with the App Setting) but are exposed globally to both PHP processes

**Comment by jtsternberg** [comment]
awesome!
